#!/bin/bash

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    print_error "Please run this script as root or using sudo"
    exit 1
fi

# Banner
echo "=========================================="
echo "   TinyProxy Auto Installer with Auth"
echo "=========================================="
echo ""

# Get configuration from user
echo "Please provide the following configuration:"
echo ""

# Get port number
while true; do
    read -p "Enter proxy port (default: 8888): " PORT
    PORT=${PORT:-8888}
    
    if [[ $PORT =~ ^[0-9]+$ ]] && [ $PORT -gt 0 ] && [ $PORT -lt 65536 ]; then
        break
    else
        print_error "Invalid port number. Please enter a number between 1 and 65535"
    fi
done

# Get username
while true; do
    read -p "Enter username for proxy authentication: " USERNAME
    if [ -n "$USERNAME" ]; then
        break
    else
        print_error "Username cannot be empty"
    fi
done

# Get password
while true; do
    read -s -p "Enter password for $USERNAME: " PASSWORD
    echo
    if [ -n "$PASSWORD" ]; then
        break
    else
        print_error "Password cannot be empty"
    fi
done

read -s -p "Confirm password: " PASSWORD_CONFIRM
echo

if [ "$PASSWORD" != "$PASSWORD_CONFIRM" ]; then
    print_error "Passwords do not match. Exiting."
    exit 1
fi

# Summary
echo ""
echo "Configuration summary:"
echo "----------------------"
echo "Port: $PORT"
echo "Username: $USERNAME" 
echo "Password: ********"
echo "Bind address: 0.0.0.0 (all interfaces)"
echo "Authentication: Single user (BasicAuth in config)"
echo ""

read -p "Proceed with installation? (y/n): " CONFIRM
if [[ ! $CONFIRM =~ ^[Yy]$ ]]; then
    print_warning "Installation cancelled"
    exit 0
fi

# Installation process
print_status "Starting installation..."

# Update system
print_status "Updating package list..."
apt update

# Install TinyProxy (apache2-utils не нужен для базовой аутентификации)
print_status "Installing TinyProxy..."
apt install -y tinyproxy

# Check if installation was successful
if [ $? -ne 0 ]; then
    print_error "Failed to install TinyProxy. Please check your internet connection and try again."
    exit 1
fi

# Backup original config
print_status "Backing up original configuration..."
cp /etc/tinyproxy/tinyproxy.conf /etc/tinyproxy/tinyproxy.conf.backup

# Create new configuration
print_status "Creating new configuration..."

cat > /etc/tinyproxy/tinyproxy.conf << EOF
# TinyProxy Configuration File
# Generated by auto-installer script

User tinyproxy
Group tinyproxy
Port $PORT
Listen 0.0.0.0
Timeout 600

# Security
DefaultErrorFile "/usr/share/tinyproxy/default.html"
StatFile "/usr/share/tinyproxy/stats.html"

# Logging
LogFile "/var/log/tinyproxy/tinyproxy.log"
LogLevel Info
Syslog On

# Connection settings
MaxClients 100
MinSpareServers 5
MaxSpareServers 20
StartServers 10
MaxRequestsPerChild 0

# Authentication - Single user
BasicAuth $USERNAME $PASSWORD

# Access control - allow from anywhere since we have authentication
Allow 0.0.0.0/0

# Headers
ViaProxyName "tinyproxy"

# HTTPS support
ConnectPort 443
ConnectPort 563
ConnectPort 993

# Additional common ports
ConnectPort 21
ConnectPort 70
ConnectPort 110
ConnectPort 995
EOF

# Set proper permissions
print_status "Setting file permissions..."
chown tinyproxy:tinyproxy /var/log/tinyproxy/ 2>/dev/null
chmod 755 /var/log/tinyproxy/ 2>/dev/null

# Secure the config file (пароль в plain text!)
chmod 600 /etc/tinyproxy/tinyproxy.conf

# Configure firewall
print_status "Configuring firewall..."
if command -v ufw > /dev/null 2>&1 && ufw status | grep -q "active"; then
    ufw allow $PORT/tcp
    print_status "Firewall rule added for port $PORT"
else
    print_warning "UFW not found or not active. Please configure your firewall manually if needed."
fi

# Start and enable service
print_status "Starting TinyProxy service..."
systemctl daemon-reload
systemctl enable tinyproxy
systemctl restart tinyproxy

# Check if service is running
if systemctl is-active --quiet tinyproxy; then
    print_status "TinyProxy is running successfully"
else
    print_error "TinyProxy failed to start. Checking logs..."
    journalctl -u tinyproxy --no-pager -l --since "5 minutes ago"
    exit 1
fi

# Get server IP
SERVER_IP=$(hostname -I | awk '{print $1}')
if [ -z "$SERVER_IP" ]; then
    SERVER_IP="your_server_ip"
fi

# Final output
echo ""
echo "=========================================="
echo "   Installation Completed Successfully!"
echo "=========================================="
echo ""
echo "Proxy Server Details:"
echo "---------------------"
echo "Server IP: $SERVER_IP"
echo "Port: $PORT"
echo "Username: $USERNAME"
echo "Password: [the password you set]"
echo ""
echo "Usage Examples:"
echo "---------------"
echo "Linux/Mac:"
echo "  export http_proxy=http://$USERNAME:$PASSWORD@$SERVER_IP:$PORT"
echo "  export https_proxy=http://$USERNAME:$PASSWORD@$SERVER_IP:$PORT"
echo ""
echo "curl:"
echo "  curl --proxy http://$USERNAME:$PASSWORD@$SERVER_IP:$PORT http://httpbin.org/ip"
echo ""
echo "wget:"
echo "  wget -e use_proxy=yes -e http_proxy=$SERVER_IP:$PORT \\"
echo "       --proxy-user=$USERNAME --proxy-password='$PASSWORD' \\"
echo "       http://example.com/file.txt"
echo ""
echo "Browser settings:"
echo "  Proxy: $SERVER_IP:$PORT"
echo "  Username: $USERNAME"
echo "  Password: [your password]"
echo ""
echo "Management Commands:"
echo "--------------------"
echo "  sudo systemctl status tinyproxy  # Check status"
echo "  sudo systemctl restart tinyproxy # Restart service"
echo "  sudo tail -f /var/log/tinyproxy/tinyproxy.log  # View logs"
echo ""
print_warning "Important Security Notes:"
print_warning "1. Password is stored in PLAIN TEXT in /etc/tinyproxy/tinyproxy.conf"
print_warning "2. For multiple users, consider using htpasswd file method"
print_warning "3. Change password regularly by editing the config file"
print_warning "4. The config file is secured with chmod 600"
echo ""
echo "To change password later:"
echo "  sudo nano /etc/tinyproxy/tinyproxy.conf"
echo "  # Edit the BasicAuth line and restart: sudo systemctl restart tinyproxy"
echo ""

# Test the proxy
print_status "Testing proxy connection..."
sleep 2
if curl --max-time 10 --proxy http://$USERNAME:$PASSWORD@localhost:$PORT http://httpbin.org/ip > /dev/null 2>&1; then
    print_status "Proxy test: SUCCESS"
else
    print_warning "Proxy test: FAILED - but service is running. Check firewall and network settings."
fi